### ISSUE TITLE
Send assigned memeberships to a keyless account instead of burning

### ISSUE THREAD

**Issue by olanod** [virto-network/frame-contrib#8]
When a membership is assigned, it's burned from the account of the group in the special "collection 0" and re-minted in a collection specific to the group that is assigning a new member. This comes with the issue that collection 0 *forgets* it ever had a given membership allowing for a membership with a given id to be re-minted. We want membership ids to remain unique across all collections, we can do that if instead of burning we transfer the membership to an account not controlled by anyone.

**Comment by pandres95** [comment]
I'll check this out today, Dani.
